frontend:
  build: frontend
  ports:
    - 8080
    - 8181
    - 9000:9000
    - 9999:80
  links:
    - scheduler
    - sonar

postgres:
  build: database
  ports:
    - 5432
  environment:
    CONCOURSE_PASSWORD_HASH: e9c57016c3f4d87870fe4e4ecb7d7a6b
    POSTGRES_PASSWORD: md5b988cfaa5ea2a14c1ec79d59a5a949f6
    SONAR_PASSWORD_HASH: b05e02d26b524e4287428984d14a6824

scheduler:
  build: scheduler
  volumes:
    - ./keys:/app/keystore
  links:
    - postgres
  environment:
    CONCOURSE_EXTERNAL_URL: http://127.0.0.1:9999/

sonar:
  build: sonar
  links:
    - postgres
  environment:
    SONARQUBE_JDBC_USERNAME: sonar
    SONARQUBE_JDBC_PASSWORD: sonar
    SONARQUBE_JDBC_URL: jdbc:postgresql://postgres/sonar

worker:
  build: worker
  links:
    - frontend
  privileged: true
  volumes:
    - ./keys:/app/keystore
