#!/bin/sh
#

myip=$(awk "/$(hostname)/ {print \$1}" /etc/hosts)
/app/bin/concourse_linux_amd64 web \
	--basic-auth-username me --basic-auth-password secret \
	--session-signing-key /app/keystore/session_signing_key \
	--tsa-host-key /app/keystore/host_key \
	--tsa-authorized-keys /app/keystore/authorized_keys \
	--postgres-data-source "postgres://concourse:password@postgres/concourse" \
	--peer-url "http://$myip:8080" \
	--external-url "$CONCOURSE_EXTERNAL_URL"
