#!/bin/sh -e
#
# vim: set ts=2 sw=2 sts=2 et:

. /app/bootstrap

cd "$PYTHON_BUILD_SOURCE"
$PIP install sphinx $PYTHON_BUILD_ADDITIONAL_PACKAGES
$PYTHON_BUILD_PYTHON setup.py build_sphinx -b html --build-dir $PYTHON_BUILD_OUTPUT
