#!/bin/sh -e
#
# vim: set ts=2 sw=2 sts=2 et:

. /app/bootstrap

cd "$PYTHON_BUILD_SOURCE"
$PIP install wheel
$PYTHON_BUILD_PYTHON setup.py sdist --dist-dir $PYTHON_BUILD_OUTPUT
$PYTHON_BUILD_PYTHON setup.py bdist_wheel --dist-dir $PYTHON_BUILD_OUTPUT
