#!/bin/sh -e
#
if test -n "$SONAR_PASSWORD_HASH"
then
	passwd="'md5$SONAR_PASSWORD_HASH'"
else
	passwd=NULL
fi

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<SQL
CREATE USER sonar WITH
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION
  LOGIN
  PASSWORD $passwd;
CREATE DATABASE sonar WITH 
  OWNER sonar TEMPLATE template0 ENCODING utf8;
GRANT ALL PRIVILEGES ON DATABASE sonar TO sonar;
SQL
